[package]
name = "lxmi-desktop"
version = "0.6.0"
description = "Linux Model Importer & Live Mod Manager"
authors = ["BYTE-CX"]
edition = "2021"

[lib]
name = "lxmi_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
lxmi-xxmi = { path = "../../../crates/lxmi-xxmi" }
lxmi-bridge = { path = "../../../crates/lxmi-bridge" }
lxmi-core = { path = "../../../crates/lxmi-core" }
lxmi-proton = { path = "../../../crates/lxmi-proton" }
lxmi-runtime = { path = "../../../crates/lxmi-runtime" }
lxmi-steam = { path = "../../../crates/lxmi-steam" }
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["json"] }
